//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Приёмная комиссия.
        /// </summary>
        internal static string AbiturientSpbuName {
            get {
                return ResourceManager.GetString("AbiturientSpbuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string HeaderTelephoneAddress {
            get {
                return ResourceManager.GetString("HeaderTelephoneAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &lt;b&gt;Поддержка Олимпиады школьников СПбГУ: &lt;/b&gt;
        ///&lt;br/&gt;тел.: +7 812 3636063
        ///&lt;br/&gt;почта: olymp@priem.pu.ru / olympiada.spbu.ru
        ///&lt;br/&gt;&lt;b&gt;Поддержка Олимпиады для студентов:&lt;/b&gt;
        ///&lt;br/&gt;почта: psrs@spbu.ru / psrs.spbu.ru.
        /// </summary>
        internal static string HeaderTelephoneAddress_old {
            get {
                return ResourceManager.GetString("HeaderTelephoneAddress_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как English Version.
        /// </summary>
        internal static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выйти.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Электронная регистрация на поселение.
        /// </summary>
        internal static string MainNavDorms {
            get {
                return ResourceManager.GetString("MainNavDorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вход для зарегистрированых.
        /// </summary>
        internal static string MainNavLogon {
            get {
                return ResourceManager.GetString("MainNavLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Регистрация.
        /// </summary>
        internal static string MainNavRegister {
            get {
                return ResourceManager.GetString("MainNavRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Олимпиада СПбГУ.
        /// </summary>
        internal static string PersonalOfficeHeaderName {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сайт СПбГУ.
        /// </summary>
        internal static string SiteSpbu_Name {
            get {
                return ResourceManager.GetString("SiteSpbu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string SpbuHeaderAddress {
            get {
                return ResourceManager.GetString("SpbuHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Санкт-Петербургский Государственный Университет.
        /// </summary>
        internal static string Spbu_Title {
            get {
                return ResourceManager.GetString("Spbu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как en.
        /// </summary>
        internal static string UILangSetCookie {
            get {
                return ResourceManager.GetString("UILangSetCookie", resourceCulture);
            }
        }
    }
}
