//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EducationInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EducationInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EducationInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний балл.
        /// </summary>
        internal static string AvgMark {
            get {
                return ResourceManager.GetString("AvgMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна, в которой находится образовательное учреждение.
        /// </summary>
        internal static string CountryEducId {
            get {
                return ResourceManager.GetString("CountryEducId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string DiplomNumber {
            get {
                return ResourceManager.GetString("DiplomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия.
        /// </summary>
        internal static string DiplomSeries {
            get {
                return ResourceManager.GetString("DiplomSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема дипломной работы.
        /// </summary>
        internal static string DiplomTheme {
            get {
                return ResourceManager.GetString("DiplomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иностранный язык.
        /// </summary>
        internal static string LanguageId {
            get {
                return ResourceManager.GetString("LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квалификация.
        /// </summary>
        internal static string PersonQualification {
            get {
                return ResourceManager.GetString("PersonQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление (специальность).
        /// </summary>
        internal static string PersonSpecialization {
            get {
                return ResourceManager.GetString("PersonSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string PersonStudyForm {
            get {
                return ResourceManager.GetString("PersonStudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год окончания обучения.
        /// </summary>
        internal static string SchoolExitYear {
            get {
                return ResourceManager.GetString("SchoolExitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название образовательного учреждения.
        /// </summary>
        internal static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип образовательного учреждения.
        /// </summary>
        internal static string SchoolTypeId {
            get {
                return ResourceManager.GetString("SchoolTypeId", resourceCulture);
            }
        }
    }
}
