//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        internal static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        internal static string ButtonSubmitText {
            get {
                return ResourceManager.GetString("ButtonSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные данные.
        /// </summary>
        internal static string HeaderPersonalInfo {
            get {
                return ResourceManager.GetString("HeaderPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гражданство.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес проживания.
        /// </summary>
        internal static string ParentInfo_Adress {
            get {
                return ResourceManager.GetString("ParentInfo_Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес проживания (родителя или законного представителя).
        /// </summary>
        internal static string ParentInfo_Adress_Message {
            get {
                return ResourceManager.GetString("ParentInfo_Adress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО родителя или законного представителя.
        /// </summary>
        internal static string ParentInfo_Name {
            get {
                return ResourceManager.GetString("ParentInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию, имя, отчество родителя или законного представителя.
        /// </summary>
        internal static string ParentInfo_Name_Message {
            get {
                return ResourceManager.GetString("ParentInfo_Name_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату рождения.
        /// </summary>
        internal static string PersonInfo_BirthDate_Message {
            get {
                return ResourceManager.GetString("PersonInfo_BirthDate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите место рождения.
        /// </summary>
        internal static string PersonInfo_BirthPlace_Message {
            get {
                return ResourceManager.GetString("PersonInfo_BirthPlace_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        internal static string PersonInfo_Name_Message {
            get {
                return ResourceManager.GetString("PersonInfo_Name_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию.
        /// </summary>
        internal static string PersonInfo_Surname_Message {
            get {
                return ResourceManager.GetString("PersonInfo_Surname_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        internal static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При сохранении информации произошли следующие ошибки:.
        /// </summary>
        internal static string ValidationSummaryHeader {
            get {
                return ResourceManager.GetString("ValidationSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже ввели данные анкеты. Изменение персональных данных участников возможно после завершения заключительного этапа Олимпиады СПбГУ..
        /// </summary>
        internal static string WarningMessagePersonLocked {
            get {
                return ResourceManager.GetString("WarningMessagePersonLocked", resourceCulture);
            }
        }
    }
}
